name: Lint Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install flake8

      - name: Run linter
        run: flake8
