name: Lint and Test Cases Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install flake8

      - name: Run linter
        run: flake8 --exclude={{cookiecutter.utility_slug}},examples/uagents_twilio/__init__.py

  test-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cookies

      - name: Cookicutter pytests
        run: |
          pytest tests
